/*
 * generated by Xtext
 */
package org.eclipse.escriptmonkey.scripting.ui.expression.xtext.ui.contentassist

import org.eclipse.escriptmonkey.scripting.ui.expression.xtext.ui.contentassist.AbstractCoreExpressionProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CoreExpressionProposalProvider extends AbstractCoreExpressionProposalProvider {
}
